### ISSUE TITLE
Quick Update

### ISSUE THREAD

**Issue by I-A-C** [I-A-C/script.module.lambdascrapers#14]
I know I was all over the place the other day trying to get this github stuff setup properly.  Thanks bearing with me while I got it straightened out.  And thank you for all the support offered.  Don't be offended if I didn't follow a suggestion offered (if you where watching, I tried all kinda stuff).

I settled on the folder structure because it made things much easier on my end.  I run an Ubuntu setup and Desktop Github is not available.  I tried running on my virtual windows box, but I wasn't satisfied.  As result, I do all my Gitwork stuff from the command line or from the website.  It'd probably be easier to learn Github through the Desktop, but easier isn't always better.

Anyway, with this folder structure, I can easily clone the repositories onto my local machine into single folder then run my favorite diff tool(Meld) and compare directly against my developmental .kodi folder(without a bunch of extra directory levels).

I pushed some updates to the various repositories and included zips for testing.  Please test and let me know if you have issues.  I'd rather work out any issues here before I add these zips into the zip folder and update the addons.xml(.md5) 

I'm going to post issues, pull/merges etc in the respective repositories going forward.

**Comment by host505** [comment]
1. Please remove the .zips from the individual repositories (eg this one).
You don't need them, because GitHub zips it up for you! Clone or download->Download zip, and it's ready to be installed on Kodi.

2. You don't have to use GitHub Desktop. I use SmartGit on win, find it way better, and it's available for Linux as well.

**Comment by I-A-C** [comment]
> Clone or download->Download zip
Didn't see that option before for the individual module because of the way the repo was setup.  

Much easier this way

**Comment by host505** [comment]
Yeah, it only appears on the initial directory of the repo - you can download as zip the whole contents of a repo.
But that's not installable on Kodi with the previous repo structure.
