### ISSUE TITLE
Updating to repo

### ISSUE THREAD

**Issue by I-A-C** [I-A-C/script.module.lambdascrapers#24]
I'm drafting a reddit post 're-releasing' Exodus Redux / Lambdascrapers and would like update the zips folder sometime today.

Any pending Pull request or Issues would not be included.  

Are we ready to go with this?

**Comment by host505** [comment]
Might wanna create a setting for this?
#20

**Comment by I-A-C** [comment]
Extra set of eyes are always better.  I take of it.

**Comment by SerpentDrago** [comment]
Also i've noticed when updateing from current "release" to the one in the github repos  that in scrapers the Change from ALL set to Lambada Set doesn't get changed .. or fucks up . this is going to cause massive support issues . 

IDK how you can force this update to the settings.xml ??

**Comment by I-A-C** [comment]
Per Kodi, settings.xml entries can be modified but not deleted.  The inability to delete old entries in the settings.xml is a real pain.

I was looking for an example of the settings.xml being deleted on install or if below a certain version number.

Since this will create a bunch of avoidable support issues, it would be best to hold off releasing this until a workable solution is found

**Comment by SerpentDrago** [comment]
can you do a redirect ? or like double variable call ? where any reference to ALL >> to Correct new setting ? ? IDK i have no idea what i'm talking about prob :)

**Comment by SerpentDrago** [comment]
Or maybe run a popup / dialog directing users to change the setting or changeing it for them . maybe on first run it asks them to choose a scraper set ?  This would only work for those running Redux though .

**Comment by SerpentDrago** [comment]
https://forum.kodi.tv/showthread.php?tid=219650

**Comment by I-A-C** [comment]
I thought I remember seeing that...

I stay away from the official Kodi forum since I play with unofficial addons.  I gotta venture back over there a bit more often.

**Comment by doko-desuka** [comment]
On cleaning up files after an update:
https://forum.kodi.tv/showthread.php?tid=335485

**Comment by I-A-C** [comment]
doko,

Very instructive!  I really appreciate your code commenting.  That is a habit I need to develop.

**Comment by doko-desuka** [comment]
Thanks. I'm trying to be more concise with comments now, though

I learned it's better to have one large comment before a block, explaining what it does, than several small comments between lines as if narrating what the code does.

**Comment by I-A-C** [comment]
I pushed a commit - Self-removing service. Cleanup after add-on update .  https://github.com/I-A-C/script.module.lambdascrapers/commit/066ef50147d31d8a6d1ee10b801de3a116b6e15e

Before you try it, I'd make a copy of the the CleanupService.py and the addon.xml files because they get deleted and/or modified. If you want to test it again, you'd have to get those files again

**Comment by drinfernoo** [comment]
@I-A-C Does this fix attempt to restore any settings that had been previously set by the user?

**Comment by jewbmx** [comment]
Went thru my pile of scrapers and got over 17 that quit working since the last update and also decided to remove 19 sloppy ones that pull too many or dont work great lol

**Comment by doko-desuka** [comment]
@I-A-C if you'd like that cleanup to remove only the scrapers that don't exist anymore from the settings file, I can take a look into doing that (similar code to the default.py that toggles them). This way the other settings would be preserved.

@host505 =D

**Comment by I-A-C** [comment]
In section"# 1) Do the actual file changes you need:"  Instead of deleting the settings file completely, I was thinking about just doing something like this,
```
if ADDON.getSetting('module.provider') != " Lambdascrapers":
    ADDON.setSetting('module.provider', " Lambdascrapers")    `
```
That would for set ALL and any other module back to Lambdascrapers.  It keeps all the providers settings the same, however, it doesn't get rid of the lingering nonexistant settings.

A variant of that toggle code would be much better.

**Comment by host505** [comment]
I don't know guys, updating from the current repo version (1.5.3) still retains the "All" scraper module, and gets no streams if won't change ls settings first.

**Comment by I-A-C** [comment]
Did you also update script.module.exdousredux to v1.0,6?

**Comment by host505** [comment]
Yes, I did.

**Comment by I-A-C** [comment]
Are you using your fork? Your branch is 4 commits behind master.

**Comment by host505** [comment]
No, I explicitly downloaded and installed the versions you uploaded [here](https://github.com/I-A-C/zips), that are gonna be on the repo.
Is it working for you?
I'll try with a clean install.

**Comment by host505** [comment]
Didn't work. Does it work for you?

**Comment by I-A-C** [comment]
On a clean Kodi 17 install with nothing else installed, it does work for me.

Did you happen to install the script.module.exodusredux-1.0.6.zip that uploaded for testing a while back?

**Comment by I-A-C** [comment]
The log shows cleanupservice.py running. That should have reset the module from All to Lambdascraper.

I tested on linux machine.  I'll borrow a windows machine and test a portable installation

**Comment by doko-desuka** [comment]
The indentation causes that block to only run if there's a userdata/addon_data/script.module.lambdascrapers/settings.xml file

I don't know if that's what's causing the problem, but in any case since it should always run, try moving it back to the first scope inside the try block. From cleanupservice:  
```
try:
    profileFolderPath = xbmc.translatePath(ADDON.getAddonInfo('profile')).decode('utf-8')
    settingsPath = os.path.join(profileFolderPath, 'settings.xml')

    # We rewrite the user settings file while ignoring all obsolete providers.
    if xbmcvfs.exists(settingsPath):
        with open(settingsPath, 'r+') as settingsFile:
            # Parse an XML tree from the settings file.
            from xml.etree import ElementTree
            tree = ElementTree.fromstring(settingsFile.read())
            currentProviders = set(getAllHosters())
            if len(currentProviders) > 0:
                # Traverse the tree backwards so we can safely remove elements on the go.
                for element in reversed(tree):
                    id = element.get('id')
                    if id and id.startswith('provider.') and id.split('.', 1)[1] not in currentProviders:
                        tree.remove(element)
                # Dump the cleaned up XML tree back to the file.
                settingsFile.seek(0)
                settingsFile.write(ElementTree.tostring(tree))
                settingsFile.truncate()
                           
    # New indentation below:
    # Reset obsolete module providers to Lambdascrapers. <----------
    if ADDON.getSetting('module.provider') not in providerSources():
        ADDON.setSetting('module.provider', ' Lambdascrapers')
except:
pass
```

**Comment by host505** [comment]
Yes, it worked for me with the new uploaded version (1.6.0).
Btw Android had the same issue too, now also resolved.
UNLEASH!!
