### ISSUE TITLE
Bob

### ISSUE THREAD

**Issue by jewbmx** [I-A-C/script.module.lambdascrapers#31]
Anyone wanna test the bob scraper out? Think there are 2 versions that work. bob.py is the one i just tested, finds its 1 result but doesnt actually play anything for me it just times out half started.

**Comment by jewbmx** [comment]
As always i ask something and then figure it out minutes later lmao. Bob is dead, the site requires you to make a free account in order to watch a flick. I dont think there is a way to bypass that besides maybe someone rewriting the scraper to have a login with a premade account added to it

**Comment by jewbmx** [comment]
Whats the odds that anybody has a working gogoanime scraper? Ive tested a couple and couldnt get em to work anymore. Starting to wonder if its my item selections that are the problem lol

**Comment by jewbmx** [comment]
Got a bob working now but still lacking the gogoanime. Trade ya some 1080p scrapers for some good toon scrapers lol

**Comment by SerpentDrago** [comment]
I know this is NOT kodi , but it could help figure out the info youneed for gogoanime ?? 

https://github.com/OpenByteDev/SourceScraper/tree/master/packages
