### ISSUE TITLE
Just a comment...

### ISSUE THREAD

**Issue by bjgood** [I-A-C/script.module.lambdascrapers#32]
You've got a good thing going here, I-A-C. You've got some really good coders hanging out here with a lot of enthusiasm. It's my new home site. I like it here.

I'd like to suggest that you add WatchNixToons (from the Incursion github). It's a great cartoon addon (that's still working great), and it needs a new home.

**Comment by jewbmx** [comment]
Doko already has lol search github for watchnixtoons and his pops up
