### ISSUE TITLE
Integrate lambdascrapers with Exodus Clones

### ISSUE THREAD

**Issue by pewkodi** [I-A-C/script.module.lambdascrapers#34]
I was able to integrate the lambda scrapers module into my Exodus clone. 

The docs on Reddit were useful but my addon would never used the lambda scrapers sources only the sources in the addon. I was was able to use the lambda sources with the following changes.

Here are the files I changed.

addon.xml for the plugin:
 <import addon="script.module.lambdascrapers" />
added category to settings.xml at bottom of the file for the plugin.video.addonname in the resources folder.
<category label="External Scrapers">
        <setting label="LambdaScrapers Settings" type="action" option="close" action="RunPlugin(plugin://script.module.lambdascrapers/?mode=LambdaSettings)"/>
    </category>
</settings>

Added lines to the sources.py files in the script.module.addon/lib/resources/modules

after line 33
try: import lambdascrapers
except: pass

after line 322:

#try: sourceDict = [(i[0], i[1], control.setting('provider.' + i[0])) for i in sourceDict]
        try: sourceDict = [(i[0], i[1], control.addon("script.module.lambdascrapers").getSetting('provider.' + i[0])) for i in sourceDict]

after line 1163:

try: from lambdascrapers import sources
        except: pass

https://github.com/pewkodi/Leviticus

**Comment by jewbmx** [comment]
Id suggest debug scraping your addon instead of using except: pass tricks lol.

**Comment by pewkodi** [comment]
i was using the linux text editor do just do minor changes and the indents all line up.. not sure why when i commit into github the indents are off. lookup at it thru vi and see if they are off.

my repo is here: https://chibo.000webhostapp.com/plugin just add the chibo repo then the video plugin.

**Comment by pewkodi** [comment]
try excepts are used if the lambda module does not get imported.
 It will use the addon sources as fallback.
ie: pretty much the same as the lambda scraper. 

Pretty good at programmming in python just not sure how kodi uses it to pass variables and see what is happening thru output and what variables are. I know there is a how to on scraping on the kodi site and
there is a a debug mode for kodi. It would be nice if i could see how the command line output would be.

**Comment by jewbmx** [comment]
Pretty sure your issues just a small error somewhere in your code. If ya upload the entire addon to github the Wise Doko might help you out with it. Think he already has a reddit page out there somewhere to help with this tho.

**Comment by jewbmx** [comment]
You ever try...

xbmcgui.Dialog ().textviewer ("data",str (name))

**Comment by pewkodi** [comment]
My addon works now. I was just pointing out what I did to get it working based on the reddit post and what i did to get it working.  

It scrapes using lambada scrapers.

Go ahead and test my addon if you like. I can look at some more debug with the xbmc dialog output.

I appreciate it,

**Comment by pewkodi** [comment]
it just add all the source to my guthub account. Corrected indents as well.

**Comment by pewkodi** [comment]
I went thru the changed files and corrected any indent or spaces. It should all be corrected. The code is working so the addon can use lambda scrapers.

Thanks for your help.
