### ISSUE TITLE
Who got beef with this project?

### ISSUE THREAD

**Issue by I-A-C** [I-A-C/script.module.lambdascrapers#36]
I know haters gonna hate and If they hating, you know you doing something right.... 

But, what's with the recent animosity toward the project?  I'm trying to understand why folks are coming here and acting like something was stolen from them.

The only thing I can think of is the inclusion of the Yoda scrapers.   When I started this, I thought Yoda was dead..  Are they upset that I haven't updated Yoda scrapers within Lambdascrapers? Or are they mad that they were even included in the first place.

One way or the other, it's probably time to get rid of those other scraper sets.

**Comment by JFG90** [comment]
Ignore the haters and keep the scraper sets, your work is amazing! Thankyou!

**Comment by SerpentDrago** [comment]
/signed . but mainly its just Coder / blamo causing bullshit . 

really . It all stems from that ass hole . 

He has a problem with almost anyone thats not him . don't worry about it .  

I won't get into it but a4k has had to deal with this asshole a long time

**Comment by JFG90** [comment]
Don't stop doing what your doing, the work you do is amazing it's it's massively appreciated !

**Comment by jewbmx** [comment]
I think its pretty funny, everyone uses someone elses code and there is 200+ addons to prove it. The average kodi use is ripping someone elses work lmao

**Comment by jewbmx** [comment]
#Free the People, Free the World!

**Comment by redditreaper** [comment]
Well ur mom, she had my beef stick lol

**Comment by redditreaper** [comment]
┳┻| _
┻┳| •.•) Daddy, Are Copy and Pasters Gone Yet?
┳┻|⊂ﾉ
┻┳|
/﹋\
(҂`_´) -NOPE, GET BACK BEHIND THE WALL
<,︻╦╤─ ҉
/﹋\

**Comment by redditreaper** [comment]
> 
> 
> I think its pretty funny, everyone uses someone elses code and there is 200+ addons to prove it. The average kodi use is ripping someone elses work lmao

Sure sharing is caring sometimes. But do we really need more people like that (you) in this community?
I get fucking high from fixing or writing a scraper, its a thrill. And i feel fucking accomplished.
Then turn around and look at all the clowns lol, copy and pasting over and over

**Comment by redditreaper** [comment]
Thought Lambda scrapers was trying to be different???? Honestly looks like the rest of the garbage like eggman, mrfreeworld, drknow99, wilson fag magic and others. Really why make this stupid scraper set when its all the same shit, same links as joe blow down the street???

**Comment by jewbmx** [comment]
community? Bitch this aint no facebook or soup kitchen, its a damn program with addons ya weirdo.  You dont like that people share and use code? Maybe you shouldnt be playing with OPENSOURCE SoftWare!  Ahh you wanna talk crap on fake accounts like a troll guess what even the github website says this is a place for what we do lol. Get a Life

**Comment by redditreaper** [comment]
lol put down to crack pipe child. u have no idea what ur talking about crack head. No shit its opensoure fucking retard. You should learn how to DO YOUR OWN SHIT. Man go back to school

**Comment by redditreaper** [comment]
community? Bitch this aint no facebook or soup kitchen, its a damn program with addons ya weirdo.

> Sure black jew boy, this statement alone shows us all what u really know about kodi development lol 
Please put down the crack pipe

**Comment by redditreaper** [comment]
> 
> 
> community? Bitch this aint no facebook or soup kitchen, its a damn program with addons ya weirdo. You dont like that people share and use code? Maybe you shouldnt be playing with OPENSOURCE SoftWare! Ahh you wanna talk crap on fake accounts like a troll guess what even the github website says this is a place for what we do lol. Get a Life

Sure jew boy, this statement alone shows us all you have no idea what kodi development is all about lol
what are u like 14?

**Comment by SerpentDrago** [comment]
Your the one acting like they are 14 . You are really heavy on the Projection man . 

Seriously , I hope you get some help . Your life seems very sad .

**Comment by SerpentDrago** [comment]
FYI , for anyone reading this , i'm sure you know , but this "redditreaper" is NOT the same person as the mod on /r/Addons4kodi

**Comment by drinfernoo** [comment]
@I-A-C, please don't remove these comments. We're reporting him, but need proof.

**Comment by SerpentDrago** [comment]
![image](https://user-images.githubusercontent.com/21133858/48310475-c08d3900-e55d-11e8-955f-ab31672846b2.png)

@I-A-C  please use these tools to help out

**Comment by redditreaper86** [comment]
So redditreaper wasn't available before but i guess it is now hence why you're trying to pretend to be me lol man this guy doesn't let up. Will you ever stop acting like a child. You want to contribute? Contribute but stop acting like a dumbass already

**Comment by jewbmx** [comment]
Must be doing something right lol everyone is using scrapers that were only dropped here or in my addon and i think you guys just got the kodi bae exodus 6.0 to update to 7.0 which looks to be a copy of your redux lol the exodus scrapers modules a sweet touch.
