### ISSUE TITLE
Lambdascrapers 1.6.0a

### ISSUE THREAD

**Issue by I-A-C** [I-A-C/script.module.lambdascrapers#39]
Seems 13clowns pushed a newer version of LS with some slight changes in the settings.xml to make lambdascrapers the default and removed some of the EnableAlls(which is exactly what I'm working on at the moment).  

I have a feeling this is gonna cause problems for folks that have both the 13clowns repo and the exodusredux repos installed.  I was testing some stuff and now i've been reverted back to previous state.

If you're gonna do your own thing 13clowns, rename the module something else and make the appropriate changes within your addon.

Additionally, the jewbmx scraper set was not included in the public release.  It was for testing purposes and has been removed from the repo.

**Comment by jewbmx** [comment]
Honestly not sure who made that folder or why lol, i figured someone would just compare the code and test it then change the proper files.

**Comment by jewbmx** [comment]
While on the subject of odd versions anybody know why the supremacy repository has the liveresolver addon at 0.1.50? Every other repository in my list has it at 0.1.49

**Comment by 13Clowns** [comment]
@I-A-C it will be removed. May I link to your repo to prevent issues in the future?

**Comment by I-A-C** [comment]
13clowns, sorry i didnt respond to your earlier request about this..

Please feel free to link to my repo.

Funny thing is i had just completed the same exact modifications, including changing the defaults to True.  I rebooted, saw your update and freaked..  it's all good now

**Comment by 13Clowns** [comment]
Thank you, I'm adding some updates and will definitely throw credits your way and the other main contributing few. @jewbmx

**Comment by jewbmx** [comment]
That little 'issue' is what i was thinking about when i suggested you have the LS in a seperate repo lol that way people could link it in and not carry all your stuff with em. Should have atleast 1 addon inside it tho like a speedtest or repo so it isnt lookin blank lol

**Comment by jewbmx** [comment]
I dont need any credit ever for anything :p im just here to watch tv lol

**Comment by 13Clowns** [comment]
Us too but there are so many haters, just showing appreciation and send some sun your way!

**Comment by jewbmx** [comment]
You should add the artwork for ER to the repo while your at it :) it kinda looks like a half removed addon lol

**Comment by bjgood** [comment]
jewbmx,
You deserve credit for your efforts, dude. I hit your github all the time to see what you've come up with. You're an asset.

Later...
