### ISSUE TITLE
Ignore .pyo files

### ISSUE THREAD

**Issue by drinfernoo** [I-A-C/script.module.lambdascrapers#4]
Simple enough, it would just help your code as be cleaner.

**Comment by jewbmx** [comment]
I just ran through the yoda sources today from the addons normal module and found these not working for me. Might help ya lol    -de-
centitar.py

-en-
hdmega.py
tvrelease.py
rlsmovies.py
rajahoki88.py
onlinedizi.py
mzmovies.py
moviesgold.py
movie4uch.py
miradetodo.py
imdark.py
freemovie6.py
fmovied6.py
filmfrantic.py
dizigold.py
ddls.py
allrls.py

--es--
megapelistv.py

--fr--
streamay.py
filmenstreaminghd.py

--ko--
kdramacool.py
dramafire.py
dramacool.py
drama4u.py

--pl--
trt.py
szukajkatv.py
paczamy.py
openkatalog.py
filmyto.py
filmwebbooster.py

--ru--
kinoxax.py

**Comment by doko-desuka** [comment]
@jewbmx you should open a new issue just for those that don't work. Your testing is valuable.

**Comment by jewbmx** [comment]
Sorry Im not very good with github lol. Pretty sure those sources i posted were sites down, im in the US so i also came across a few blocked ones and like 20 more with ddos protection that dont seem to work in yoda.

**Comment by doko-desuka** [comment]
Oh I'm not the owner of this repository, that'd be @I-A-C  

But it's useful to know which scrapers need an update anyway :)
