### ISSUE TITLE
Gaia and lambdascrapers

### ISSUE THREAD

**Issue by I-A-C** [I-A-C/script.module.lambdascrapers#40]
Here is snippet of code in plugin.video/gaia/resources/lib/providers/external/universal/open/lamscrapersx.py

```
	def _instancesPrepare(self):
		pathSource = tools.System.path(tools.Extensions.IdLamScrapers)
		pathDestination = self._instancesPath()
		file = 'addon.xml'
		fileSource = tools.File.joinPath(pathSource, file)
		fileDesitnation = tools.File.joinPath(pathDestination, file)
		if not tools.File.exists(fileDesitnation) or not tools.Hash.fileSha1(fileSource) == tools.Hash.fileSha1(fileDesitnation):
			tools.File.copyDirectory(pathSource, pathDestination)
			self._instancesRename(pathDestination)
		self._instancesInclude()
		return tools.File.joinPath(pathDestination, 'lib', 'lambdascrapers', 'sources_ALL')
```

 I haven't had a chance to go through all of Gaia's code to see where this goes.  But I'm curious what impact if any does the "sources_ALL' call have on the lambdascraper module?

**Comment by redditreaper86** [comment]
IAC i already have a fixed version of this so all good. Gaia team has just been busy working on Leia update so they haven't pushed it yet. I'll probably be pushing out an update including my fix until they release their update
