### ISSUE TITLE
Scraper Settings resetting when closing kodi 

### ISSUE THREAD

**Issue by SerpentDrago** [I-A-C/script.module.lambdascrapers#42]
https://old.reddit.com/r/Addons4Kodi/comments/9w9ikl/providers_resetting/

https://www.reddit.com/r/Addons4Kodi/comments/9v5py4/lambda_scrapers_uninstalling/

I keep day after day after day . Get posts about this "issue" 

Its got to be something screwy with that cleanupservice.py thing

**Comment by SerpentDrago** [comment]
https://www.reddit.com/r/Addons4Kodi/comments/9y3ja9/exodus_redux_keeps_reverting_providers_option/

and another.... seriously guys can anything be done?

**Comment by jewbmx** [comment]
Best way to fix that issue is to stay off reddit :)

**Comment by jewbmx** [comment]
Any chance these issues could be caused by something dumb and small like not having a __init__.py with LS's settings or having different versions of files in the module folders? (ExoRedux /modules vs LS /modules)
