### ISSUE TITLE
rlsbb

### ISSUE THREAD

**Issue by sergio49650** [I-A-C/script.module.lambdascrapers#45]
I have made some changes in rlsbb.py script to simplify and get more results
Would you like to get them ?

**Comment by SerpentDrago** [comment]
Make a Pull request with your changes and i'm sure I-A-C will review and choose to include it or not . 

Thanks

**Comment by JFG90** [comment]
Yes please that would be amazing!

**Comment by I-A-C** [comment]
@sergio49650,  I don't have debrid, but I'm sure others would be very interested to see your rlsbb.py

**Comment by sergio49650** [comment]
I updated my fork yesterday for debrid scrapers (rlsbb, rlsscn, 2ddl, 
directdl) and 1 en scraper (darewatch)

I was used to have good results with darewatch, but it didn't worked 
anymore since few weeks.

Now it runs again.

**Comment by SerpentDrago** [comment]
@sergio49650 can i pull those changes ? or can you add it to a PR for my fork ? or update this one ? 

I'd like any changes you have made

**Comment by sergio49650** [comment]
If you can pull, pull everything you want 😁If you can't I will send them-------- Message original --------Objet : Re: [I-A-C/script.module.lambdascrapers] rlsbb (#45)De : SerpentDrago À : "I-A-C/script.module.lambdascrapers	" Cc : sergio49650 ,Mention	 @sergio49650 can i pull those changes ? or can you add it to a PR for my fork ? or update this one ?
I'd like any changes you have made

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/I-A-C/script.module.lambdascrapers","title":"I-A-C/script.module.lambdascrapers","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/I-A-C/script.module.lambdascrapers"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SerpentDrago in #45: @sergio49650 can i pull those changes ? or can you add it to a PR for my fork ? or update this one ? \r\n\r\nI'd like any changes you have made"}],"action":{"name":"View Issue","url":"https://github.com/I-A-C/script.module.lambdascrapers/issues/45#issuecomment-445557400"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/I-A-C/script.module.lambdascrapers/issues/45#issuecomment-445557400",
"url": "https://github.com/I-A-C/script.module.lambdascrapers/issues/45#issuecomment-445557400",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [I-A-C/script.module.lambdascrapers] rlsbb (#45)",
"sections": [
{
"text": "",
"activityTitle": "**SerpentDrago**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@SerpentDrago",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"I-A-C/script.module.lambdascrapers\",\n\"issueId\": 45,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"I-A-C/script.module.lambdascrapers\",\n\"issueId\": 45\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/I-A-C/script.module.lambdascrapers/issues/45#issuecomment-445557400"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 413148042\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by SerpentDrago** [comment]
Next time if you can , click view on github , if you reply directly in email , it posts all that crap :)

**Comment by SerpentDrago** [comment]
Thanks !  PR, seems to work great !

**Comment by jewbmx** [comment]
My email has an option to uncheckmark all that spare info lol
