### ISSUE TITLE
ScraperTesting

### ISSUE THREAD

**Issue by jewbmx** [I-A-C/script.module.lambdascrapers#7]
I finally got far enough into the scraper testing and cleaning to upload em. Instead of doing like doko said i decided to make a new repo called ScraperHub to store them in, that way you can go thru em and see if i messed up anywhere and use what you want lol.
Plus im really github stupid and dont know exactly how to work everything :)

**Comment by bjgood** [comment]
jewbmx,
How about posting a link to ScraperHub. I'd like to go thru it.

**Comment by jewbmx** [comment]
my bad knew i forgot something lol https://github.com/jewbmx/ScraperHub/tree/master/files

**Comment by I-A-C** [comment]
jewbmx,
You still working on this?  I wanted to included your cleaned up scraper list in an future Lambdascrapers release.  I grabbed a copy of the files directory before you took it down.  Not sure if it's the latest version.

Check out issues  #16 - Adding Scraper Sets
